### PR TITLE
Fix typos in 03_ticket_v1/12_outro test 

### PR DESCRIPTION
**Pull request by oliverbarnes**

### CODE REVIEW

**Comment by oliverbarnes** [comment]
The build is failing when trying to checkout https://github.com/mainmatter/core-sans-a-fonts. Error says the checkout action doesn't find the default branch, but when explicitly setting the branch as 'main', it doesn't find the repo at all. 

(I've since removed the troubleshooting commit that tried to set the ref)

Found these related issues, but no clear solution (to me) - might be related to permissions:

https://github.com/actions/checkout/issues/347
https://github.com/actions/checkout/issues/417

I'm setting this PR as draft until I'm able to resolve it. Luca, hopefully you'll have a clear idea of what's going on :)

**Comment by LukeMathWalker** [comment]
I don't know about the permissions (@marcoow?), but the refs there are intentional!
At this stage we haven't yet discussed `Copy` types.

**Comment by marcoow** [comment]
Yeah, you don't have access to the repo from a fork – I see that's a bit limiting, maybe we shouldn't be building the PDF on forks or use a fallback font or so…

**Comment by marcoow** [comment]
@LukeMathWalker wdyt? Shall we just build `main`?

**Comment by LukeMathWalker** [comment]
We could use a fallback font, so that we are sure it builds correctly at the very least.

**Comment by marcoow** [comment]
yeah I agree that's better 👍

**Comment by oliverbarnes** [comment]
> but the refs there are intentional!
> At this stage we haven't yet discussed Copy types.

Ok! I wasn't familiar with values as references like this :) I'll close this and go back to the exercise, then

**Review by Magkoooh — APPROVED** [review]

**Pull request closed without merging**
